## set comiple options
if(ENABLE_DEBUG)
    set(CMAKE_BUILD_TYPE Debug FORCE)
else()
    set(CMAKE_BUILD_TYPE Release FORCE)
    add_compile_options(-Ofast)
    add_compile_options(-ffast-math)
    add_compile_options(-Os)
    add_compile_options(-DNDEBUG)
endif()

if (USE_OPENMP)
    add_compile_options(-fopenmp)
endif()

add_compile_options(-std=c++11)
add_compile_options(-fPIC)
add_compile_options(-ldl)
add_compile_options(-pie)
add_compile_options(-lc)

add_compile_options(-W)
add_compile_options(-Wall)
add_compile_options(-Wno-unused-variable) # no unused-variable
add_compile_options(-Wformat)
add_compile_options(-Winit-self)
add_compile_options(-Wpointer-arith)
add_compile_options(-Wno-shadow)
add_compile_options(-fpermissive)
add_compile_options(-Wsign-promo)
add_compile_options(-fdiagnostics-show-option)
add_compile_options(-Wno-undef)
add_compile_options(-Wno-narrowing)
add_compile_options(-Wno-unknown-pragmas)
add_compile_options(-Wno-delete-non-virtual-dtor)
add_compile_options(-Wno-comment)
add_compile_options(-Wno-sign-compare)
add_compile_options(-Wno-ignored-qualifiers)
add_compile_options(-Wno-enum-compare)
add_compile_options(-Wno-unused-parameter)
add_compile_options(-Wno-unused-function)
add_compile_options(-Wno-unused-command-line-argument)


